### PR TITLE
Further try to fix yaml cpp...

### PR DESCRIPTION
**Pull request by helenol**
If this does not fix jenkins compiling issues I think we should just write our own Jenkins :P

@bloesch

### CODE REVIEW

**Comment by helenol** [comment]
test this please

**Comment by bloesch** [comment]
this yaml stuff is annoying, feels like its compiling successfully at times. thinking about getting rid of yaml-cpp and using the opencv parser.

**Comment by helenol** [comment]
test this please

**Comment by helenol** [comment]
Yeah, it's super crappy. :/ Really depends on what's installed on the system, compilation order, etc.

**Comment by helenol** [comment]
test this please

**Comment by bloesch** [comment]
is something changing on Jenking? the master branch compiled successfully end of last week...

**Comment by helenol** [comment]
test this please

**Comment by helenol** [comment]
It depends which machine it runs on too, Burri's PR failed originally due to yaml stuff.
Trying to get it to build consistently across all slaves, currently messing with jenkins config.

**Comment by bloesch** [comment]
ok, thanks for looking into this, if it ends up being too annoying let me know and I'll spend 1/2 day to get rid of yaml-cpp

**Comment by helenol** [comment]
I *think* may have just gotten it. Let me know if builds keep randomly failing due to YAML stuff, will take another look. :)

**Comment by bloesch** [comment]
thank you very much. feel free to merge.

**Pull request merged**
