### PR TITLE
Adapted to new LWF, split and structured visionCommon, worked on multiCam version

### PR DESCRIPTION
**Pull request by bloesch**
Sorry about the big commit. Would be glad if someone could compile and test it on their PC. Requires the feature/generalizedInformationFilter branch of lightweight_filtering.

### CODE REVIEW

**Comment by helenol** [comment]
Add to whitelist

**Comment by helenol** [comment]
add to whitelist (for real this time) (will test on bluebird shortly)

**Comment by helenol** [comment]
@bloesch : fails to compile on jenkins (sometimes it's useful!) http://129.132.38.183:8080/job/rovio/28/label=ubuntu/parsed_console/ is the errors

**Comment by bloesch** [comment]
I guess you still have the master branch on lightweight_filtering? ->  feature/generalizedInformationFilter

**Comment by helenol** [comment]
Sweet, thanks! Just tested on euroc6 (one of the new asctec platforms), compiles and works great. :) Thanks!

LGTM

**Pull request merged**
